ALTER TABLE "SYSTEM"."CARTITEMS"
ADD "QUANTITY" NUMBER DEFAULT 1 NOT NULL;

ALTER TABLE "SYSTEM"."PRODUCTS"
ADD "USERID" NUMBER;

ALTER TABLE "SYSTEM"."PRODUCTS"
ADD CONSTRAINT "FK_PRODUCTS_USERS" FOREIGN KEY ("USERID")
    REFERENCES "SYSTEM"."USERS" ("USERID") ON DELETE SET NULL ENABLE;