INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (1, 500.00, 'Credit Card', 10101, 'City A', 'Address 1');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (2, 1200.50, 'PayPal', 20202, 'City B', 'Address 2');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (3, 750.99, 'Debit Card', 30303, 'City C', 'Address 3');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (4, 300.00, 'Credit Card', 40404, 'City D', 'Address 4');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (5, 1999.99, 'Bank Transfer', 50505, 'City E', 'Address 5');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (6, 450.00, 'Credit Card', 60606, 'City F', 'Address 6');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (7, 99.99, 'PayPal', 70707, 'City G', 'Address 7');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (8, 850.75, 'Debit Card', 80808, 'City H', 'Address 8');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (9, 220.00, 'Credit Card', 90909, 'City I', 'Address 9');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (10, 599.99, 'Bank Transfer', 10010, 'City J', 'Address 10');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (11, 320.00, 'Credit Card', 11111, 'City K', 'Address 11');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (12, 1000.00, 'PayPal', 12121, 'City L', 'Address 12');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (13, 780.00, 'Debit Card', 13131, 'City M', 'Address 13');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (14, 450.50, 'Credit Card', 14141, 'City N', 'Address 14');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (15, 1300.99, 'Bank Transfer', 15151, 'City O', 'Address 15');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (16, 550.00, 'Credit Card', 16161, 'City P', 'Address 16');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (17, 80.99, 'PayPal', 17171, 'City Q', 'Address 17');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (18, 900.00, 'Debit Card', 18181, 'City R', 'Address 18');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (19, 250.00, 'Credit Card', 19191, 'City S', 'Address 19');

INSERT INTO SYSTEM.ORDERS (USERID, TOTALAMOUNT, PAYMENTMETHOD, ZIPCODE, CITY, ADDRESS)
VALUES (20, 650.49, 'Bank Transfer', 20202, 'City T', 'Address 20');
